//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace luxuryShop.Models.Enity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int OrderID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string OrderName { get; set; }
        public string OrderMobile { get; set; }
        public string OrderAddress { get; set; }
        public string OrderEmail { get; set; }
    }
}
